version: "3"

services:
  surrealdb:
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - -A
      - --auth
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
    volumes:
      - /surrealdb:/surrealdb
